name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  schedule:
    - cron: '* * * * *'  # Ejecuta cada minuto (¡solo para pruebas!)

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      VARIABLE_PRUEBA: "¡Soy una variable de entorno de prueba!"  # Define tu variable aquí

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Print secret variable
        env:
          VARIABLE_PRUEBA: ${{ secrets.VARIABLE_PRUEBA }}  # Referencia al secret
        run: |
          echo "El valor del secreto es: $VARIABLE_PRUEBA"
          echo "Nota: GitHub ocultará este valor en los logs con '***'."
          echo "Hora actual: $(date)"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
