name: Ping Supabase to Prevent Pausing

on:
  schedule:
    - cron: '0 9 * * 1,4' 
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use Node.js 18

      - name: Install Supabase Client
        run: npm install @supabase/supabase-js --force

      - name: Ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }} # Supabase project URL
          SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }} # Supabase service role key
        run: |
          node -e "
          (async () => {
            try {
              // Debugging: Log environment variables (optional)
              console.log('Supabase URL:', process.env.SUPABASE_URL);
              console.log('Supabase Key:', process.env.SUPABASE_KEY);

              // Import Supabase client
              const { createClient } = require('@supabase/supabase-js');
              const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);

              // Ping Supabase by querying a table (e.g., 'songs')
              const { data, error } = await supabase.from('tt-task-list').select('*').limit(1);

              // Handle errors
              if (error) throw error;

              // Log success
              console.log('Ping successful:', data);
            } catch (err) {
              // Log and exit with error
              console.error('Error pinging Supabase:', err.message);
              process.exit(1);
            }
          })();
          "
